### ISSUE TITLE
파이썬 내장함수인 max함수 사용

### ISSUE THREAD

**Issue by yunju727** [SongGaHyeon/pythonfor_Datastructure#1]
max함수를 사용하면 더 간단하게 할 수 있을 것 같아요.
(652146c8751d498f910d9731582be9429449fadc)

**Comment by SongGaHyeon** [comment]
max함수 이용해서 수정했습니다!

**Comment by SongGaHyeon** [comment]
max 함수 이용해 해봤습니다!
